### ISSUE TITLE
`test-watch` is broken

### ISSUE THREAD

**Issue by tizmagik** [NYTimes/kyt#269]
Fresh checkout of `kyt` and then `npm run test-watch` gives an error:

```
2016-10-24 14:45 node[97090] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null)
 (-22)
2016-10-24 14:45 node[97090] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null)
 (-22)
2016-10-24 14:45 node[97090] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null)
 (-22)
events.js:160

      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1012:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)
```

This seems to also happen in projects using `kyt#master`.

**Comment by hanbzu** [comment]
I'm experiencing the same issue with a completely different repository based on create-react-app. Could it be a Webpack thing?

**Comment by tizmagik** [comment]
Thanks @hanbzu yea, it looks like it's actually an issue in Jest/Watchman:

https://github.com/facebook/jest/issues/1767

Apparently, uninstalling or reinstalling Watchman fixes the issue for some folks.

I'll leave this issue open to track the upstream issue.
