### ISSUE TITLE
fs.writeFile throws ERR_INVALID_CALLBACK

### ISSUE THREAD

**Issue by koebeen** [NYTimes/kyt#566]
### Versions of kyt, node, OS
kyt 0.9.0
node 10.6.0
OS macos 10.11.6
### Bug or Feature?
Bug
### Current Behavior
yarn dev or npm run dev results in an error
### Desired Behavior
no error is thrown. app runs.

### Fix:
line 72 of webpack.base.js shoud read:
            `fs.writeFileSync(assetsFilePath, JSON.stringify(assets, null, '  '), 'utf8');`
instead of:
            `fs.writeFile(assetsFilePath, JSON.stringify(assets, null, '  '), 'utf8');`

full error:
```
fs.js:133
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:133:9)
    at Object.writeFile (fs.js:1132:14)
    at WebpackAssetsManifest.done (/kyt/papieren-helden/node_modules/kyt/config/webpack.base.js:72:16)
    at WebpackAssetsManifest.emit (events.js:182:13)
    at Compiler.applyPlugins (/kyt/papieren-helden/node_modules/tapable/lib/Tapable.js:61:14)
    at /kyt/papieren-helden/node_modules/webpack/lib/Compiler.js:273:13
    at Compiler.emitRecords (/kyt/papieren-helden/node_modules/webpack/lib/Compiler.js:369:37)
    at /kyt/papieren-helden/node_modules/webpack/lib/Compiler.js:267:12
    at /kyt/papieren-helden/node_modules/webpack/lib/Compiler.js:362:11
    at next (/kyt/papieren-helden/node_modules/tapable/lib/Tapable.js:218:11)
```

**Comment by awayken** [comment]
@koebeen I've been running into this, too. I had to ensure that I was running on Node 8 (which is the LTS right now). I hope this helps!

**Comment by stmathew7** [comment]
Yep, using Node 8 resolved the same error for me as well.

**Comment by koebeen** [comment]
thanks guys. yeah, obvious in the end. i should have run the lts..

**Comment by fesebuv** [comment]
@koebeen @awayken 
Is this issue resolved? Could it be closed?
Thanks.

**Comment by stmathew7** [comment]
Yes, please close it

**Comment by jackgray** [comment]
Is Node v8 required to use kyt? I'm getting invalid callback error when following getting started instructions verbatim. If this is the case, it seems that either updating kyt to work with Node 10 or mentioning in the ReadMe that Node 8 is required would be appropriate, as Node 10.x is listed as the current LTS version.

**Comment by DataRogue** [comment]
Node v10 is now LTS, when can we expect a solution for this?

**Comment by kierandesmond** [comment]
What worked for me, was editing webpack-version-file-plugin > index

`VersionFile.prototype.writeFile = function(templateContent){
	var self = this;
	fileContent = ejs.render(templateContent, self.options);
    fs.writeFile(self.options.outputFile, fileContent, {flag: 'w'}, function() {});
}`

Note after the flag options, I just added a blank callback function. Then the build continued unhindered. Hope this helps someone.
